/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafica;
import javax.swing.JLabel;
import javax.swing.JList;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Color;
import javax.swing.SwingConstants;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JComboBox;
import javax.swing.LayoutStyle.ComponentPlacement;

import Logica.*;
import javax.swing.JButton;

/**
 *
 * @author kevin
 */
public class BasedeDatos extends javax.swing.JFrame {
	private Operaciones op = new Operaciones();
	
    /**
     * Creates new form BasedeDatos
     */
    public BasedeDatos() {
    	
        initComponents();
        this.setLocationRelativeTo(null);
        
        op.Inicializar(getComboBox());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelTopbar = new javax.swing.JPanel();
        jLblPioneras = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPnlRigthbar = new javax.swing.JPanel();
        jLabel_foto = new javax.swing.JLabel();
        jLabel_Nacimiento = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_Nacionalidad = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_Fallecimiento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_Nombre.setEditable(false);
        jTextField_SegundoNombre = new javax.swing.JTextField();
        jTextField_SegundoNombre.setEditable(false);
        jTextField_Apellido = new javax.swing.JTextField();
        jTextField_Apellido.setEditable(false);
        jTextField_SegundoApellido = new javax.swing.JTextField();
        jTextField_SegundoApellido.setEditable(false);
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextField_Logros = new javax.swing.JTextField();
        jTextField_Logros.setEditable(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField_Ocupacion = new javax.swing.JTextField();
        jTextField_Ocupacion.setEditable(false);
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblSidebar = new javax.swing.JLabel();
        jBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTopbar.setBackground(new java.awt.Color(117, 117, 189));

        jLblPioneras.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLblPioneras.setForeground(new java.awt.Color(255, 255, 255));
        jLblPioneras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblPioneras.setText("DATOS");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 153, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("X");

        jComboBox1.setFont(new java.awt.Font("Noto Sans Cond", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Seleccione una opcion"}));
        jComboBox1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               op.cambiarDatos(jComboBox1, jTextField_Nombre, jTextField_SegundoNombre, jTextField_Apellido,
            		   jTextField_SegundoApellido, jLabel_Nacionalidad, jLabel_Nacimiento, jLabel_Fallecimiento, 
            		   jTextField_Logros, jTextField_Ocupacion, jLabel_foto);
            }
        });

        javax.swing.GroupLayout jPanelTopbarLayout = new javax.swing.GroupLayout(jPanelTopbar);
        jPanelTopbar.setLayout(jPanelTopbarLayout);
        jPanelTopbarLayout.setHorizontalGroup(
            jPanelTopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopbarLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jLblPioneras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTopbarLayout.setVerticalGroup(
            jPanelTopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLblPioneras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelTopbarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelTopbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 50));

        jPnlRigthbar.setBackground(new java.awt.Color(204, 204, 255));

        //jLabel_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/BarbaraThoens.jpg"))); // NOI18N
        jLabel_foto.setText("");
        jLabel_foto.setInheritsPopupMenu(false);

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel8.setText("Lugar:");

        jLabel10.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel10.setText("Fallecimiento:");

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel3.setText("Nacimiento:");

        javax.swing.GroupLayout jPnlRigthbarLayout = new javax.swing.GroupLayout(jPnlRigthbar);
        jPnlRigthbarLayout.setHorizontalGroup(
        	jPnlRigthbarLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPnlRigthbarLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPnlRigthbarLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPnlRigthbarLayout.createSequentialGroup()
        					.addComponent(jLabel_foto, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
        					.addGap(0, 0, Short.MAX_VALUE))
        				.addGroup(jPnlRigthbarLayout.createSequentialGroup()
        					.addGroup(jPnlRigthbarLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel8)
        						.addComponent(jLabel3)
        						.addComponent(jLabel10))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPnlRigthbarLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel_Fallecimiento, GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        						.addComponent(jLabel_Nacionalidad)
        						.addComponent(jLabel_Nacimiento, GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))))
        			.addContainerGap())
        );
        jPnlRigthbarLayout.setVerticalGroup(
        	jPnlRigthbarLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPnlRigthbarLayout.createSequentialGroup()
        			.addComponent(jLabel_foto, GroupLayout.PREFERRED_SIZE, 220, GroupLayout.PREFERRED_SIZE)
        			.addGap(34)
        			.addGroup(jPnlRigthbarLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(jLabel_Nacimiento))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPnlRigthbarLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8)
        				.addComponent(jLabel_Nacionalidad))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPnlRigthbarLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel10)
        				.addComponent(jLabel_Fallecimiento))
        			.addContainerGap(108, Short.MAX_VALUE))
        );
        jPnlRigthbar.setLayout(jPnlRigthbarLayout);

        jPanel2.add(jPnlRigthbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 430));

        jTextField_Nombre.setText("Primer Nombre");
        jTextField_Nombre.setName(""); // NOI18N
        jTextField_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, -1));

        jTextField_SegundoNombre.setText("Segundo Nombre");
        jPanel2.add(jTextField_SegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 120, -1));

        jTextField_Apellido.setText("Primer Apelllido");
        jPanel2.add(jTextField_Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 120, -1));

        jTextField_SegundoApellido.setText("Segundo Apellido");
        jPanel2.add(jTextField_SegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 120, -1));

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel2.setText("Segundo Apellido");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel4.setText("Primer Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Segundo Nombre");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel6.setText("Primer Apelllido");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        jTextField_Logros.setText("");
        jScrollPane2.setViewportView(jTextField_Logros);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 310, 320));

        jTextField_Ocupacion.setText("");
        jScrollPane1.setViewportView(jTextField_Ocupacion);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 180, 180));

        jLabel12.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Ocupaci\u00F3n");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 140, -1));

        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Logros");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 140, -1));

        lblSidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/_bdc01532-51f0-4b78-b8c3-033019be1cb0_1.jpeg"))); // NOI18N
        lblSidebar.setText("imagen");
        jPanel2.add(lblSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 120, 430));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));
        
        jBtnSalir.setBackground(new java.awt.Color(117, 117, 189));
        jBtnSalir.setForeground(new java.awt.Color(204, 204, 204));
        jBtnSalir.setText("X");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasedeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasedeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasedeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasedeDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasedeDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel_foto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel_Fallecimiento;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Nacimiento;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Nacionalidad;
    private javax.swing.JLabel jLblPioneras;
    private JTextField jTextField_Logros;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTopbar;
    private javax.swing.JPanel jPnlRigthbar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_SegundoNombre;
    private javax.swing.JTextField jTextField_Apellido;
    private javax.swing.JTextField jTextField_SegundoApellido;
    private JTextField jTextField_Ocupacion;
    private javax.swing.JLabel lblSidebar;
    /**
     * @wbp.nonvisual location=589,424
     */
    // End of variables declaration//GEN-END:variables
    
    /**
     * Agrega un elemento al JComboBox.
     */
    public void addtoComboBox(String nombre) {
        jComboBox1.addItem(nombre);
    }
    
    /**
     * Obtiene el JComboBox.
     */
    public JComboBox getComboBox() {
        return jComboBox1;
    }
    
    /**
     * Obtiene el JTextField del primer nombre.
     */
    public JTextField getTextFiel_Nombre() {
        return jTextField_Nombre;
    }
    
    /**
     * Obtiene el JTextField del segundo nombre.
     */
    public JTextField getTextFiel_SegundoNombre() {
        return jTextField_SegundoNombre;
    }
    
    /**
     * Obtiene el JTextField del primer apellido.
     */
    public JTextField getTextFiel_Apellido() {
        return jTextField_Apellido;
    }
    
    /**
     * Obtiene el JTextField del segundo apellido.
     */
    public JTextField getTextFiel_SegundoApellido() {
        return jTextField_SegundoApellido;
    }
    
    /**
     * Obtiene el JLabel de la fecha de nacimiento.
     */
    public JLabel getLabel_Nacimiento() {
        return jLabel_Nacimiento;
    }
    
    /**
     * Obtiene el JLabel de la nacionalidad.
     */
    public JLabel getLabel_Nacionalidad() {
        return jLabel_Nacionalidad;
    }
    
    /**
     * Obtiene el JLabel de la fecha de fallecimiento.
     */
    public JLabel getLabel_Fallecimiento() {
        return jLabel_Fallecimiento;
    }
    
    /**
     * Obtiene la JList de logros.
     */
    public JTextField getList_Logros() {
        return jTextField_Logros;
    }
    
    /**
     * Obtiene el JTextPane de ocupación.
     */
    public JTextField getList_Ocupacion() {
        return jTextField_Ocupacion;
    }
}
