/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafica;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.SwingConstants;

import Logica.*;

/**
 * Clase que representa la ventana principal de la aplicación.
 */
public class FrmPrincipal extends javax.swing.JFrame {
    // Declaración de objetos estáticos de Operaciones y BasedeDatos
    private static Operaciones op = new Operaciones();
    private static BasedeDatos bd = new BasedeDatos();
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents(); // Inicialización de componentes de la interfaz
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Declaración de componentes de la interfaz
        bg = new javax.swing.JPanel();
        lblSidebar = new javax.swing.JLabel();
        jPanelTopbar = new javax.swing.JPanel();
        jLblPioneras = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPnlEntrar = new javax.swing.JPanel();
        jLblEntrar = new javax.swing.JLabel();
        jPnlDatos = new javax.swing.JPanel();
        jLblIntegrantes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jBtnEntrar = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pioneras");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(854, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setEnabled(false);
        bg.setMinimumSize(new java.awt.Dimension(854, 480));
        bg.setPreferredSize(new java.awt.Dimension(854, 480));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/_bdc01532-51f0-4b78-b8c3-033019be1cb0_1.jpeg"))); // NOI18N
        lblSidebar.setText("imagen");
        bg.add(lblSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 220, 480));

        jPanelTopbar.setBackground(new java.awt.Color(117, 117, 189));
        jPanelTopbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblPioneras.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLblPioneras.setForeground(new java.awt.Color(255, 255, 255));
        jLblPioneras.setText("PIONERAS");
        jPanelTopbar.add(jLblPioneras, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 6, 237, -1));

        jLabel1.setBackground(new java.awt.Color(117, 117, 189));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jPanelTopbar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        bg.add(jPanelTopbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 50));

        jPnlEntrar.setBackground(new java.awt.Color(204, 153, 255));

        jLblEntrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLblEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jLblEntrar.setText("           Entrar");
        jLblEntrar.setHorizontalTextPosition(SwingConstants.CENTER);

        javax.swing.GroupLayout jPnlEntrarLayout = new javax.swing.GroupLayout(jPnlEntrar);
        jPnlEntrarLayout.setHorizontalGroup(
            jPnlEntrarLayout.createParallelGroup(Alignment.LEADING)
                .addComponent(jLblEntrar, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPnlEntrarLayout.setVerticalGroup(
            jPnlEntrarLayout.createParallelGroup(Alignment.TRAILING)
                .addComponent(jLblEntrar, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPnlEntrar.setLayout(jPnlEntrarLayout);

        bg.add(jPnlEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 40));

        jPnlDatos.setBackground(new java.awt.Color(243, 242, 242));

        jLblIntegrantes.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLblIntegrantes.setText("Integrantes:");


        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 2, 12)); // NOI18N
        jLabel2.setText("Mateo Gonzalez");

        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 2, 12)); // NOI18N
        jLabel3.setText("Kevin Tadeo");

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel4.setText("Institución:");

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 2, 12)); // NOI18N
        jLabel5.setText("Escuela Técnica Superior de Las Piedras");

        jLabel6.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel6.setText("Dirección:");

        jLabel7.setFont(new java.awt.Font("Roboto Condensed", 2, 12)); // NOI18N
        jLabel7.setText("Baltasar Brum N° 665 esq. Pilar Cabrera");

        jLabel8.setFont(new java.awt.Font("Roboto Condensed", 1, 12)); // NOI18N
        jLabel8.setText("Docentes:");

        jLabel9.setFont(new java.awt.Font("Roboto Condensed", 2, 12)); // NOI18N
        jLabel9.setText("Gustavo Dentone");

        jLabel10.setFont(new java.awt.Font("Roboto Condensed", 2, 12)); // NOI18N
        jLabel10.setText("Elizabeth Izquierdo");

        jLabel11.setFont(new java.awt.Font("Noto Serif Cond", 0, 12)); // NOI18N
        jLabel11.setText("NetBeans IDE 21");

        jLabel12.setFont(new java.awt.Font("Noto Serif Cond", 0, 12)); // NOI18N
        jLabel12.setText("Eclipse IDE for Java Developers - 2024-03");

        javax.swing.GroupLayout jPnlDatosLayout = new javax.swing.GroupLayout(jPnlDatos);
        jPnlDatos.setLayout(jPnlDatosLayout);
        jPnlDatosLayout.setHorizontalGroup(
            jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblIntegrantes)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlDatosLayout.createSequentialGroup()
                        .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                        .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnlDatosLayout.createSequentialGroup()
                        .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPnlDatosLayout.setVerticalGroup(
            jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblIntegrantes)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12))
        );

        bg.add(jPnlDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 630, 280));

        jBtnEntrar.setText("ENTRAR");
        jBtnEntrar.setHorizontalTextPosition(SwingConstants.CENTER);
        jBtnEntrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jBtnEntrarMouseDragged(evt);
            }
        });
        jBtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEntrarActionPerformed(evt);
            }
        });
        bg.add(jBtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 40));

        jBtnSalir.setBackground(new java.awt.Color(117, 117, 189));
        jBtnSalir.setForeground(new java.awt.Color(204, 204, 204));
        jBtnSalir.setText("X");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        bg.add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEntrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEntrarMouseDragged
        // TODO your handling code here:
    }//GEN-LAST:event_jBtnEntrarMouseDragged

    private void jBtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEntrarActionPerformed
        bd.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_jBtnEntrarActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
            System.exit(0);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
        
        Operaciones op = new Operaciones(); // Crea una instancia de Operaciones
        op.Inicializar(bd.getComboBox()); // Inicializa los componentes relacionados con Operaciones
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jBtnEntrar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblEntrar;
    private javax.swing.JLabel jLblIntegrantes;
    private javax.swing.JLabel jLblPioneras;
    private javax.swing.JPanel jPanelTopbar;
    private javax.swing.JPanel jPnlDatos;
    private javax.swing.JPanel jPnlEntrar;
    private javax.swing.JLabel lblSidebar;
    // End of variables declaration//GEN-END:variables
}
