/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafica;

/**
 *
 * @author kevin
 */
public class Promedios extends javax.swing.JFrame {

    /**
     * Creates new form Promedios
     */
    public Promedios() {
        initComponents();
          this.setLocationRelativeTo(null);    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        lblSidebar = new javax.swing.JLabel();
        jPanelTopbar = new javax.swing.JPanel();
        jLblPromedios = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        jBtnSalir = new javax.swing.JButton();
        ScrollOcupacion = new javax.swing.JScrollPane();
        jListOcupacion = new javax.swing.JList<>();
        ScrollNacionalidad = new javax.swing.JScrollPane();
        jListNacionalidad = new javax.swing.JList<>();
        TxtfOcupacion = new javax.swing.JTextField();
        TextfNacionalidad = new javax.swing.JTextField();
        jLblNacionalidad = new javax.swing.JLabel();
        jLblOcupacion1 = new javax.swing.JLabel();
        jPnlBase = new javax.swing.JPanel();
        jLblBase = new javax.swing.JLabel();
        jBtnBase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSidebar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/_bdc01532-51f0-4b78-b8c3-033019be1cb0_1.jpeg"))); // NOI18N
        lblSidebar.setText("imagen");
        Bg.add(lblSidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 170, 490));

        jPanelTopbar.setBackground(new java.awt.Color(117, 117, 189));
        jPanelTopbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblPromedios.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLblPromedios.setForeground(new java.awt.Color(255, 255, 255));
        jLblPromedios.setText("PROMEDIOS");
        jPanelTopbar.add(jLblPromedios, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 300, -1));

        Exit.setBackground(new java.awt.Color(117, 117, 189));
        Exit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Exit.setForeground(new java.awt.Color(204, 153, 255));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        jPanelTopbar.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        Bg.add(jPanelTopbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 50));

        jBtnSalir.setBackground(new java.awt.Color(117, 117, 189));
        jBtnSalir.setForeground(new java.awt.Color(204, 204, 204));
        jBtnSalir.setText("X");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        Bg.add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jListOcupacion.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ScrollOcupacion.setViewportView(jListOcupacion);

        Bg.add(ScrollOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 220, 210));

        jListNacionalidad.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ScrollNacionalidad.setViewportView(jListNacionalidad);

        Bg.add(ScrollNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 210));
        Bg.add(TxtfOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 200, 40));
        Bg.add(TextfNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 200, 40));

        jLblNacionalidad.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLblNacionalidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblNacionalidad.setText("Nacionalidad");
        Bg.add(jLblNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 140, -1));

        jLblOcupacion1.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLblOcupacion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblOcupacion1.setText("Ocupación");
        Bg.add(jLblOcupacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 140, -1));

        jPnlBase.setBackground(new java.awt.Color(204, 153, 255));

        jLblBase.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLblBase.setForeground(new java.awt.Color(255, 255, 255));
        jLblBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblBase.setText("Volver");
        jLblBase.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPnlBaseLayout = new javax.swing.GroupLayout(jPnlBase);
        jPnlBase.setLayout(jPnlBaseLayout);
        jPnlBaseLayout.setHorizontalGroup(
            jPnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblBase, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPnlBaseLayout.setVerticalGroup(
            jPnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblBase, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        Bg.add(jPnlBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 210, 40));

        jBtnBase.setText("ENTRAR");
        jBtnBase.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jBtnBaseMouseDragged(evt);
            }
        });
        jBtnBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBaseActionPerformed(evt);
            }
        });
        Bg.add(jBtnBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 210, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnBaseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnBaseMouseDragged
        // TODO your handling code here:
    }//GEN-LAST:event_jBtnBaseMouseDragged

    private void jBtnBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBaseActionPerformed
        BasedeDatos newframe = new BasedeDatos();
        newframe.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jBtnBaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Promedios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JLabel Exit;
    private javax.swing.JScrollPane ScrollNacionalidad;
    private javax.swing.JScrollPane ScrollOcupacion;
    private javax.swing.JTextField TextfNacionalidad;
    private javax.swing.JTextField TxtfOcupacion;
    private javax.swing.JButton jBtnBase;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLblBase;
    private javax.swing.JLabel jLblNacionalidad;
    private javax.swing.JLabel jLblOcupacion1;
    private javax.swing.JLabel jLblPromedios;
    private javax.swing.JList<String> jListNacionalidad;
    private javax.swing.JList<String> jListOcupacion;
    private javax.swing.JPanel jPanelTopbar;
    private javax.swing.JPanel jPnlBase;
    private javax.swing.JLabel lblSidebar;
}
